# typescript@5.0.0 の moduleResolution: bundler を使うためにしばらくの間 pnpm にする
# typescript@5.0.0 の pnp-patch がまだ出てないため
# deno エコシステムの `import xxx from './xxx.ts'` を解決するために moduleResolution: bundler が必要
nodeLinker: pnpm
yarnPath: .yarn/releases/yarn-3.3.1.cjs
