[dev]
  autoLaunch = false
  command = "parcel src/app/index.html"

[build]
  publish = "dist/"
  command = "parcel build src/app/index.html"

[functions]
  deno_import_map = "./netlify/edge-functions/import_map.json"

[[edge_functions]]
  path = "/api/*"
  function = "api"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
